# Generated by Django 3.0.3 on 2020-03-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxpert', '0004_auto_20200324_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
