# Generated by Django 3.0.3 on 2020-03-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxpert', '0005_auto_20200324_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(default=0, max_length=12),
        ),
    ]
