# Generated by Django 3.0.3 on 2020-03-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxpert', '0006_auto_20200324_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
