# Generated by Django 3.0.7 on 2020-09-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxpert', '0008_auto_20200707_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
